# Generated by Django 3.1 on 2020-08-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50, verbose_name='Nombre')),
                ('tipo', models.TextField(max_length=50, verbose_name='Tipo')),
                ('precio', models.IntegerField(max_length=10, verbose_name='Precio')),
                ('cantidad', models.IntegerField(max_length=20, verbose_name='Cantidad')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edicion')),
            ],
        ),
    ]
