# Generated by Django 3.1 on 2020-08-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
