# Generated by Django 3.1 on 2020-09-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20200814_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='cantidad',
            field=models.IntegerField(max_length=20, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
