# Generated by Django 3.1 on 2020-09-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_articulo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion'),
        ),
    ]
