# Generated by Django 3.1 on 2020-09-07 23:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_auto_20200907_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, max_length=50, null=True, verbose_name='Descripcion'),
        ),
    ]
